language: node_js

node_js:
  - 0.10

env:
  - secure: "C1/WbBwHSz2ABZYRJUZHKt9Qx0zdiAYdyHKo30Q1sXxet+Tz8HxlXpNa4R/NnrRQfG0q0Hx61d+vlIHCLBkqVZc8oIhI0VYfoJ3UDGVZ5TAjSpgV9gDE4mxgJ02Gm9bPsD/46QW0u9yoVEMT7bzyMulPSDKBNsHFrRnUApFQ/kk="

before_script:
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter

script: grunt test --verbose

after_script:
  - codeclimate < report/lcov.info

deploy:
  provider: releases
  api_key:
    secure: "bEN+Af0Hc9DIGtuKgKYMxwiNTJlVmUGrjVHkZBe7nzKYlc4ntWSJW+rjVOhowD1RsH3sC+cTvSS0JlHE65EFdVBMXZbgVbpcOSuapgh8aPz0dqXdRtk4GVQupNWbR8pcDScULX+aTxzjY0g473Wt6Rz8GqNwlnxG7s6La/BUfNU="
  file: build/jquery.addressfield.min.js
  on:
    repo: tableau-mkt/jquery.addressfield
    tags: true
    branch: master
